Add backup functionality to windows_task
chef/chef pull request #10894
Opened 2021-01-18 21:55 UTC by kimbernator

Adds backup property to windows_task, allowing the XML of the task to be saved for rollback purposes.

## Description
Allows rollbacks and history for windows tasks modified or deleted by chef

## Related Issue
https://github.com/chef/chef/issues/10883

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2021-01-18 22:16 UTC, tas50 commented on lib/chef/resource/windows_task.rb
> +        introduced: "17.1", default: 5,
This would be 17.0

2021-01-19 01:23 UTC, kimbernator commented on lib/chef/resource/windows_task.rb
> +        introduced: "17.1", default: 5,
Fixed

2021-01-19 03:25 UTC, jaymzh approved these changes
This looks great! Thanks!

@tas50 lmk if you disagree, but I don't think unittests are super required here - all the backup logic is part of - and tested by the backup class and it's unittests. The only thing that tests backups is the file_spec, and it's just checking that the resource specified the right types/default.

2021-01-19 03:38 UTC, jaymzh requested changes
Oops, I missed that the tests that are failing are super related:

```
  1) Chef::Util::Backup backup_path uses the configured Chef::Config[:file_backup_path] and strips the drive on windows
```

2021-01-19 17:51 UTC, jaymzh approved these changes
Looks good. The end2end test failures look unrelated, but heads up to @tas50 looks like a bad runlist somewhere.

2021-01-20 03:50 UTC, merged

2021-01-20 03:50 UTC, tas50 commented
Thanks @kimbernator