bump ruby versions everywhere
chef/chef pull request #10922
Opened 2021-01-22 20:40 UTC by lamont-granquist

2021-01-22 20:44 UTC, tas50 commented on .expeditor/verify.pipeline.yml
> +  # Tests Ruby 2.7
chef-utils and chef-config were still on ruby 2.6 by design. These tests need to stay

2021-01-22 22:49 UTC, jaymzh approved these changes
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia3.giphy.com%2Fmedia%2FxT9DPrC1YWXBO1coyQ%2Fgiphy.gif&token=lgtm" data-gitmeme-token="lgtm"><img src="https://media3.giphy.com/media/xT9DPrC1YWXBO1coyQ/giphy.gif" title="Created by gitme.me with /lgtm"
        alt="lgtm"/></a>

2021-01-22 23:14 UTC, tas50 requested changes
We need 2.7 and 3.0 testing to match our previous 2.6 and 2.7 testing. 2.7 doesn't need to be testing every single bit, but it should still touch it.

2021-01-22 23:26 UTC, tas50 commented
Add this to the .rubocop.yml to reduce the Chefstyle warnings:


```yaml
# This cop shouldn't alert on the helper / specs itself
Chef/Ruby/LegacyPowershellOutMethods:
  Exclude:
    - 'lib/chef/mixin/powershell_out.rb'
    - 'spec/functional/mixin/powershell_out_spec.rb'
```

2021-01-27 16:25 UTC, tas50 commented
@lamont-granquist if you rebase this the chefstyle issue should go away

2021-03-11 23:09 UTC, tas50 commented on Gemfile
> +gem "ffi", git: "https://github.com/ffi/ffi", branch: "master", submodules: true
Do we still need this now that 1.15 is out?

2021-03-16 02:36 UTC, tas50 commented on chef.gemspec
> +  s.add_dependency "ffi" # FIXME: needs to be >= 1.14.3 at some point
we should just make this 1.15 for the m1 stuff

2021-03-18 17:37 UTC, merged