Switch the kitchen tests to Policyfiles
chef/chef pull request #11119
Opened 2021-02-27 05:54 UTC by tas50

Test what we recommend

Signed-off-by: Tim Smith <tsmith@chef.io>

2021-02-27 20:12 UTC, lamont-granquist approved these changes

2021-05-18 08:37 UTC, damacus commented on .github/workflows/kitchen.yml
> +      uses: actionshub/chef-install@master
```suggestion
      uses: actionshub/chef-install@main
```

actionshub has switched to the main branch now and @Xorima is looking to remove the master branch shortly 👍🏼

2021-05-18 08:37 UTC, damacus requested changes
master --> main branch for actionshub chef-installs

2021-05-18 08:46 UTC, Xorima requested changes

2021-05-18 08:46 UTC, Xorima commented on .github/workflows/kitchen.yml
> +      uses: actionshub/chef-install@master
```suggestion
      uses: actionshub/chef-install@main
```

2021-05-18 21:34 UTC, damacus approved these changes

2021-05-19 13:44 UTC, Xorima approved these changes

2021-08-02 17:40 UTC, lamont-granquist approved these changes

2021-08-03 07:11 UTC, Xorima commented
Leave the windows side with me and I will try to get a fix in for it

2022-02-10 18:32 UTC, closed without merging