Remove the legacy osc_compat mode
chef/chef pull request #11361
Opened 2021-04-13 23:01 UTC by tas50

This provides compatibility with Chef Server 11. It's time to remove
this.

Signed-off-by: Tim Smith <tsmith@chef.io>

2021-04-13 23:10 UTC, tas50 commented
Fixes https://github.com/chef/chef/issues/8116

2021-04-19 17:00 UTC, jaymzh approved these changes

2021-04-19 17:02 UTC, jaymzh commented
looking over test failures, they're unrelated... but there's a lot, someone should double-check before merging they're not related.

2021-06-17 04:20 UTC, kagarmoe requested changes
![tenor-93260980](https://user-images.githubusercontent.com/4400151/122330808-ab809f80-cee8-11eb-814c-24ddb44817d1.gif)

2021-06-17 04:20 UTC, kagarmoe commented on lib/chef/chef_fs/config.rb
> +              the case please use 'hosted_everything' or allow repo_mode to default}
```suggestion
              the case, use 'hosted_everything' or allow 'repo_mode' to default}
```

2021-07-26 23:52 UTC, closed without merging

2021-07-26 23:52 UTC, tas50 commented
We have the deprecation which is enough for now