Fix PEM file generation when user is created
chef/chef pull request #12619
Opened 2022-02-21 11:59 UTC by sanjain-progress

Fix PEM file generation when user created via knife. 
This issue arises because of changes in infra API response. And create_key is missing from body params.

## Description

## Related Issue

- https://github.com/chef/chef-workstation/issues/2505

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2022-02-21 16:52 UTC, marcparadise requested changes
This looks good, but we'll need to add tests and probably modify existing tests that look in the wrong place (`user_create_spec.rb`) 
Does chef client still support server API v0? If so, this should handle both types of response, based on the version.

2022-02-21 19:54 UTC, i5pranay93 approved these changes

2022-02-21 21:00 UTC, lamont-granquist commented
Yeah this should really get validated on some older chef-server versions, at a minimum it should be validated against the last chef-server 12.x version.

Since there's no end-to-end integration testing this needs to get done manually against an old chef-server.

There's also a question here around why this knife command isn't failing in the integration tests in this repo that hit a chef-zero server and if there's drift between chef-server and chef-zero.  I guess there doesn't seem to be any integration test though that tests `knife user`:

https://github.com/chef/chef/tree/main/knife/spec/integration

At the very least one spec test around this failure case should get added under a new `user_create_spec.rb` there (and ideally validate that it fails before and succeeds after).

I also don't really understand what is going on with the server versioning here.  It looks like knife itself is not using the API objects, so I expect server versioning to complete in the rest object properly but then knife is not using versioning code (which is why I expect to see breakage on either old or new chef-servers).

I kind of suspect the right fix here is to change knife user completely to use the Chef::User objects and do versioning properly, this fix sets off alarm bells in my head that this is just pushing around failures between old and new versions of the API.

2022-03-02 07:42 UTC, sanjain-progress commented
> Yeah this should really get validated on some older chef-server versions, at a minimum it should be validated against the last chef-server 12.x version.
> 
> Since there's no end-to-end integration testing this needs to get done manually against an old chef-server.
> 
> There's also a question here around why this knife command isn't failing in the integration tests in this repo that hit a chef-zero server and if there's drift between chef-server and chef-zero. I guess there doesn't seem to be any integration test though that tests `knife user`:
> 
> https://github.com/chef/chef/tree/main/knife/spec/integration
> 
> At the very least one spec test around this failure case should get added under a new `user_create_spec.rb` there (and ideally validate that it fails before and succeeds after).
> 
> I also don't really understand what is going on with the server versioning here. It looks like knife itself is not using the API objects, so I expect server versioning to complete in the rest object properly but then knife is not using versioning code (which is why I expect to see breakage on either old or new chef-servers).
> 
> I kind of suspect the right fix here is to change knife user completely to use the Chef::User objects and do versioning properly, this fix sets off alarm bells in my head that this is just pushing around failures between old and new versions of the API.

@lamont-granquist Verify these changes to the older chef-server 12.x version. And knife create command works and PEM key gets generated. 

Added test cases for both scenarios fail and pass

And I am not sure why Chef::User objects are not used. My guess is to make a knife gem independent of chef-server completely or can be some other past parameter.

2022-03-15 19:46 UTC, lamont-granquist approved these changes

2022-03-15 19:48 UTC, merged