Adds 'makecache_fast' property to `yum_repository` minimise cached repodata
chef/chef pull request #12915
Opened 2022-05-24 13:20 UTC by lanky

## Description
adds a `makecache_fast` property to the `yum_repository` resource/provider, to enable downloading only the minimum require metadata when refreshing the cache

in recent RHEL releases (and possibly other related distros like CentOS etc) additional multi-Gb metadata is downloaded by the standard `yum makecache` command, which is fairly wasteful of both disk space and bandwidth, for example:

```
total 8.9G
-rw-rw-r-- 1 root root 629M Aug 23  2021 filelists.xml
-rw-r--r-- 1 root root 330M May 24 04:30 filelists.xml.sqlite
-rw-rw-r-- 1 root root 3.6G Aug 23  2021 other.xml
-rw-r--r-- 1 root root 3.7G May 24 04:32 other.xml.sqlite
-rw-r--r-- 1 root root 374M Aug 23  2021 primary.xml
-rw-r--r-- 1 root root 454M May 23 05:01 primary.xml.sqlite
-rw-r--r-- 1 root root  23M Aug 23  2021 updateinfo.xml
```

the only way to avoid this appears to be to use `yum makecache fast`, which does not fetch the larger files listed above.  An example from the same system as above:

```
total 850M
-rw-rw-r-- 1 root root 374M Aug 23  2021 primary.xml
-rw-r--r-- 1 root root 454M May 24 04:38 primary.xml.sqlite
-rw-rw-r-- 1 root root  23M Aug 23  2021 updateinfo.xml
```

This PR adds the `makecache_fast` boolean to the `yum_repository` resource, defaulting to false, which allows makecache fast to be used on a per-repository basis if required

## Related Issue
None

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [X] I have read the **CONTRIBUTING** document.
- [X] I have run the pre-merge tests locally and they pass.
- [x] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.
- [X] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2022-05-31 19:37 UTC, tpowell-progress commented
@lanky Is this Ready for Review? If so, please change from draft to ready for review so that we can review and approve.

2022-08-23 19:36 UTC, jaymzh commented
closed/reopened to kick off tests again

2022-08-23 19:56 UTC, jaymzh commented
OK this looks good. However @marcparadise wants to wait until next week after the Chef 18 gem is shipped

2022-11-29 21:02 UTC, jaymzh requested changes
Sorry for the delay. With 18 out now, we're clearing the backlog. Can you rebase onto `main`, and if the tests pass we're ready to go. The tests are all passing now on `main`.

2022-12-13 20:04 UTC, jaymzh commented
ping @gheeney

2022-12-15 09:40 UTC, lanky commented
rebased onto main, well technically I recreated and reapplied the commits as the constant rebase conflicts between various versions of the Gemfile and various ruby version files were driving me crazy. But this is now main + my proposed additions

2022-12-20 20:25 UTC, tpowell-progress commented
@jaymzh Tagging you back for re-review and also to float it up to the top of my sort.

2022-12-29 21:28 UTC, jaymzh approved these changes
LGTM!

2023-01-03 20:05 UTC, merged