[Chef-16] Fix solaris build and test failures in adhoc pipeline
chef/chef pull request #13240
Opened 2022-10-13 14:22 UTC by neha-p6

Signed-off-by: Neha Pansare <neha.pansare@progress.com>

## Description
This change backports fixes here https://github.com/chef/chef/pull/13230/, adding as new commits instead of cherrypick as there are multiple commits

Solaris builds are failing with error
`export/home/chef-ci/builds/chef/chef-chef-chef-16-omnibus-adhoc/omnibus/vendor/bundle/ruby/3.1.0/bundler/gems/omnibus-83d8428abde4/lib/omnibus/health_check.rb:108:in `block (2 levels) in run!': undefined method `include?' for nil:NilClass (NoMethodError)
 
          bad_omnibus_libs, bad_omnibus_bins = bad_libs.keys.partition { |k| k.include? "embedded/lib" }
                                                                              ^^^^^^^^^`
 This change updates the omnibus SHA in omnibus/Gemfile.lock so as to pull in those fixes from 
 (https://github.com/chef/omnibus/pull/1083)
 (https://github.com/chef/omnibus/pull/1082)

Details about test failures are [here](https://chefio.atlassian.net/browse/INFC-274)                                                                            

## Related Issue

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2022-10-13 14:27 UTC, neha-p6 commented
Adhoc build testing this change https://buildkite.com/chef/chef-chef-chef-16-omnibus-adhoc/builds/51

2022-10-18 19:58 UTC, jaymzh requested changes
Minor change to not further break builds/tests.

2022-10-18 19:58 UTC, jaymzh commented on spec/functional/shell_spec.rb
> +      ENV["TERM"] = "vt100" if ["", "unknown"].include?(ENV["TERM"].to_s)
Lets fix the trailing whitespace here?

2022-10-19 09:33 UTC, neha-p6 commented on spec/functional/shell_spec.rb
> +      ENV["TERM"] = "vt100" if ["", "unknown"].include?(ENV["TERM"].to_s)
Done.

2022-10-19 10:06 UTC, johnmccrae approved these changes

2022-10-19 10:45 UTC, merged