Update deprecated "hab sup status" call
chef/chef pull request #13314
Opened 2022-11-01 23:07 UTC by gene1wood

## Description

This changes "hab sup status" calls to "hab svc status" calls to avoid this deprecation notice :

> * ruby_block[wait-for-sup-default-startup] action runØ 'hab sup status' as an alias for 'hab svc status' is deprecated. Please update your automation and processes accordingly.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2022-11-08 12:00 UTC, johnmccrae commented
This is a great catch. Is there any reason to leave the blocks with "sup" in their title? I think it would be more readable to update those as well

From:
`ruby_block "wait-for-sup-default-startup" do`

To:
`ruby_block "wait-for-svc-default-startup" do`

2022-11-08 12:00 UTC, johnmccrae requested changes
Can you change the block titles from "sup" to "svc"?

2022-11-08 20:07 UTC, tpowell-progress approved these changes

2022-11-08 20:11 UTC, tpowell-progress commented
Do Not Merge label due to [habitat tests](https://buildkite.com/chef/chef-chef-main-habitat-test) being broken... clear label once pipeline is back to green

2022-11-17 17:30 UTC, gene1wood commented
@tpowell-progress just so you know [that link to the habitat tests](https://buildkite.com/chef/chef-chef-main-habitat-test) is to something internal to Progress as it requires a login using Progress's Office 365 SSO and so it's not visible to folks outside Progress.

Do any of the merged fixes related to habitat in #13316 or #13340 relate to the broken hab / test pipeline?

2022-11-28 18:55 UTC, gene1wood commented
@johnmccrae Would you clear the "Changes requested" flag? The change was added in [9d4aaef](https://github.com/chef/chef/pull/13314/commits/9d4aaef16b33bcb3a19513b23b85355cd0f80ccd)

2022-11-29 20:41 UTC, merged