Fix indentation of condition for disabling repos
chef/chef pull request #13327
Opened 2022-11-03 22:10 UTC by darnaut

## Description
Fix handling of `--enablerepo` and `--disablerepo` options in `yum_package`.

There's an indentation error in `yum_helper.py` which was causing `disable` options to be ignored unless it appeared last in the `repos` array of the command sent to the Yum helper.  The order of the `repos` field is not deterministic as the command hash is converted to a JSON object before being sent to the helper:

```
[2022-11-03T17:06:48+00:00] TRACE: sending '{"action":"whatavailable","provides":"containerd-1.6.6-1.amzn2","repos":[{"disable":"*"},{"enable":"amzn2extra-docker"}]}' to python helper
```

This was also hiding another problem where the helper failed to re-enable repos when all repos are disabled using a wildcard (e.g. "*") as it attempts to `getRepo('*')` which leads to an error. Since rpmdb is closed before and after every query with an `--enablerepo` or `--disablerepo` option, the code that attempts to restore state is simply removed.

## Related Issue
N/A

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2022-11-03 23:45 UTC, darnaut commented
I suspect this would still be broken for cases like `--disablerepo==* --enablerepo=foo` and the order changes when being converted to `[{"enable":"foo"}, {"disable":"*"}]` for whatever reason.

2022-11-08 20:50 UTC, tpowell-progress commented on lib/chef/provider/package/yum/yum_helper.py
> +    # XXX: Reset any repos we were passed in enablerepo/disablerepo to the original state
I would recommend either deleting the comment or commenting how the exit state of this function resets the enabled/disabled state.

2022-11-08 20:51 UTC, tpowell-progress requested changes
Adjust the comment on line 124 vs. leaving an XXX comment.

2022-11-29 20:52 UTC, jaymzh approved these changes
Assuming tests pass.

Also we should backport this to 17 and 16?

2022-12-13 20:04 UTC, jaymzh commented
@darnaut - can you fix your tests, please?

2022-12-13 20:20 UTC, tpowell-progress commented
INFC-381 created for spell check

2022-12-13 20:21 UTC, merged