feat(ulimits): additional ulimit options
chef/chef pull request #13394
Opened 2022-11-30 14:56 UTC by chrisminton

## Description

- add as, cpu, maxlogins, msgqueue, rss, sigpending options to the `user_ulimit` resource
## Related Issue

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2022-11-30 15:05 UTC, Daemonali approved these changes

2023-01-23 02:56 UTC, johnmccrae commented
Can you add some tests in for these new options please?

2023-01-23 09:45 UTC, chrisminton commented
Hi @johnmccrae there are additions for the `kitchen-tests` section - this is currently the only place that ulimit options are being interrogated. Is there something you'd like me to add?

2023-01-31 21:07 UTC, tpowell-progress commented
> Hi @johnmccrae there are additions for the `kitchen-tests` section - this is currently the only place that ulimit options are being interrogated. Is there something you'd like me to add?

@chrisminton Thanks for pointing those out. I think we're good with those.

2023-01-31 21:10 UTC, jaymzh requested changes
one small bug.

2023-01-31 21:10 UTC, jaymzh commented on lib/chef/resource/user_ulimit.rb
> +            msgqueue_hard_limit: new_resource.msgqueue_hard_limit,
this isn't in the template at all.

2023-01-31 21:38 UTC, chrisminton commented on lib/chef/resource/user_ulimit.rb
> +            msgqueue_hard_limit: new_resource.msgqueue_hard_limit,
fixed thanks @jaymzh

2023-02-28 20:45 UTC, jaymzh requested changes

2023-10-17 19:46 UTC, johnmccrae commented
@chrisminton Can you add the test that Phil requested?

2023-10-18 09:42 UTC, chrisminton commented on kitchen-tests/cookbooks/end_to_end/recipes/linux.rb
> +  maxlogins_hard_limit 10
done @jaymzh

2023-10-24 20:54 UTC, tpowell-progress approved these changes

2023-10-24 20:56 UTC, tpowell-progress commented
@chrisminton Looks like the Buildkite build is broken due to an old configuration file. Can you rebase on main, please?

2023-11-14 17:56 UTC, tpowell-progress commented
Approving workflows and tagging for community PR review.

2023-11-16 00:03 UTC, merged