Updated post Chef-18 to clarify how to release
chef/chef pull request #13428
Opened 2022-12-12 20:03 UTC by johnmccrae

Signed-off-by: John <john.mccrae@progress.com>

## Description

## Related Issue

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2022-12-12 20:13 UTC, tpowell-progress commented on docs/dev/how_to/releasing_chef_infra.md
> +   1. WARNING: Any resource that inherits it's basic structure from a parent resource is likely to comingle settings from both when you run that command. For example, there are 17-20 resources that c
should be `commingle`

2022-12-12 20:14 UTC, tpowell-progress commented on docs/dev/how_to/releasing_chef_infra.md
> +   2. One tool you can use to help yourself is Beyond Compare. If you have to buy it, it's like 20$
`20$` -> `$20`

2022-12-12 20:15 UTC, tpowell-progress requested changes
See suggestions

2022-12-12 22:19 UTC, johnmccrae commented on docs/dev/how_to/releasing_chef_infra.md
> +   1. WARNING: Any resource that inherits it's basic structure from a parent resource is likely to comingle settings from both when you run that command. For example, there are 17-20 resources that c
corrected

2022-12-12 22:21 UTC, johnmccrae commented on docs/dev/how_to/releasing_chef_infra.md
> +   2. One tool you can use to help yourself is Beyond Compare. If you have to buy it, it's like 20$
corrected

2022-12-13 00:45 UTC, tpowell-progress approved these changes

2022-12-13 03:59 UTC, merged