launchd - array instead of a hash for Apple's associated_bundle_ident…
chef/chef pull request #13477
Opened 2023-01-06 04:02 UTC by Arequ

Should address the issue where the launchd.rb resource requires a hash instead of an array per Apple's docs. 
 #13476

2023-01-10 20:44 UTC, tpowell-progress commented on lib/chef/resource/launchd.rb
> +      property :associated_bundle_identifiers, Array,
Seems like this needs to at a minimum be isolated to only macOS platforms. Would also like to see some testing around this to ensure that it's being handled correctly for macOS and non-macOS platforms

2023-01-10 20:45 UTC, tpowell-progress commented
Approved the workflows to see if there's any current breakage, but need to revisit.

2023-01-10 20:46 UTC, tpowell-progress requested changes
Add tests and verify that non-macOS platforms aren't broken.

2023-01-12 01:51 UTC, Arequ commented
> Add tests and verify that non-macOS platforms aren't broken.

This resource should only be applicable to macos per the documentation so I went ahead and restricted it to the darwin platform. I also added a kitchen test to verify that it causes an exception on Linux as it's supposed to. 

The kitchen actions are failing due to other resources and they can be observed failing in the most recent main branch commit. Please review the failed kitchen run and confirm this change is related.

I tried removing the line that was creating the error in the linux end-to-end test but it produced another error in the resulting action. Somethings going on with the way the Amazon Linux container is being spun up and tested on.

I'm not sure how to address the existing issues but this change should not introduced any additional problems. In its current state, it is creating plist files on macOS Ventura that are not valid.

Please advise on how to proceed, I'd like to continue using this resource on macOS.

2023-01-17 20:37 UTC, jaymzh commented on README.md
> +#
remove this?

2023-01-17 20:38 UTC, tpowell-progress commented
@Arequ Please rebase on `main` to resolve the conflict.

2023-01-17 21:12 UTC, Arequ commented on README.md
> +#
done

2023-01-17 21:15 UTC, Arequ commented
> @Arequ Please rebase on `main` to resolve the conflict.

@tpowell-progress, completed. Please pardon that I missed the DCO/obvious fix tagging. I would probably classify this as an "obvious fix". Should I make any changes to include this?

2023-01-19 17:26 UTC, tpowell-progress commented
> > @Arequ Please rebase on `main` to resolve the conflict.
> 
> @tpowell-progress, completed. Please pardon that I missed the DCO/obvious fix tagging. I would probably classify this as an "obvious fix". Should I make any changes to include this?

@Arequ Looks like you lost the DCO on the rebase.

2023-01-24 21:02 UTC, tpowell-progress commented
> > > @Arequ Please rebase on `main` to resolve the conflict.
> > 
> > 
> > @tpowell-progress, completed. Please pardon that I missed the DCO/obvious fix tagging. I would probably classify this as an "obvious fix". Should I make any changes to include this?
> 
> @Arequ Looks like you lost the DCO on the rebase.

@Arequ, I misread your comment, but I think we want DCO on this.

2023-02-09 22:23 UTC, Arequ commented
updated

2023-02-09 22:35 UTC, erikng commented
Can we get this merged? It should have been a one line change and the current version that shipped was obviously never used or tested to begin with. It simply does not work.

I understand asking for tests, but it makes little sense for the one line change to turn into what it has been.

2023-02-14 20:52 UTC, tpowell-progress commented
@tpowell-progress Something is broken with the verify pipeline... checking in with build team first before merging this in case there's something broken that I'm not seeing.

2023-02-14 20:54 UTC, jaymzh approved these changes
Assuming tests (other than the centos6 buildkite ones) pass.

2023-02-14 21:19 UTC, merged