Example of bash recource doubled escape characters
chef/chef pull request #13509
Opened 2023-01-17 17:55 UTC by sean-horn

## Description
Let's show an example of doubled escape characters.

The chef-client bash interpreter gets one, and find gets one.

Signed-off-by: Sean Horn <sean_horn@opscode.com>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [X] I have read the **CONTRIBUTING** document.
- [X] I have run the pre-merge tests locally and they pass.
- [X] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [X] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2023-01-17 19:40 UTC, IanMadd approved these changes

2023-01-17 19:55 UTC, IanMadd commented on lib/chef/resource/bash.rb
> +
```suggestion

      **Using escape characters in a string of code**

      In the following example, the `find` command uses an escape character (`\`). Use double escape characters (`\\`) to preserve it in the code string:

```

2023-01-17 20:40 UTC, tpowell-progress requested changes
@sean-horn Please resolve trailing whitespace linting errors and Ian's suggestion and we can work on getting this merged in.

2023-01-22 07:52 UTC, johnmccrae approved these changes

2023-01-24 16:04 UTC, sean-horn commented
@tpowell-progress Done. I have adopted @IanMadd 's suggestion.

2023-01-24 20:12 UTC, jaymzh approved these changes

2023-01-24 20:18 UTC, merged