Inspect lazy result
chef/chef pull request #13570
Opened 2023-02-10 00:21 UTC by steakknife

Show lazy results in logs and stack traces.

Signed-off-by: Barry Allard <ball@meta.com>

## Description

`  path #<Chef::DelayedEvaluator:0x012345812384 path/to/file>` is unhelpful in resource logs and stack traces. This change fixes that. It assumes dumb, non-idempotent stuff doesn't happen in the lazy evaluation runtime phase. This will hopefully go away when `unified_mode` is possible to use with our API cookbook model.

`  path lazy { (evaluates to) "C:\Program Files\Foobar\Widgets.exe" }`

`  path lazy { (evaluates to) "/home/foo/.your-magic-file" }`

are much nicer.

## Related Issue

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:
- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2023-02-10 01:17 UTC, steakknife reviewed
It would be nice(tm) to hacky cache the results of a previous `#call(*)` but it's a frozen object in some environments. It's more useful to show the value by call()'ing again than to consider edge-cases with non-idempotent side-effects.

2023-02-14 20:40 UTC, jaymzh approved these changes
This seems sane to me. I don't know much about the delayed evaluator, but if the tests pass I'm cool with this.

2023-03-07 20:21 UTC, tpowell-progress commented
@steakknife can you clean up the linting errors and also re-sign the DCO @dafyddcrosby is looking into this to see if there a DCO issue as well.

2023-03-14 19:25 UTC, marcparadise commented on spec/unit/delayed_evaluator_spec.rb
> +# Author:: Adam Jacob (<adam@chef.io>)
Please remove these Author entries from the header

2023-03-14 19:34 UTC, marcparadise commented on spec/unit/delayed_evaluator_spec.rb
> +# Author:: Seth Chisamore (<schisamo@chef.io>)
```suggestion
```

2023-05-16 20:13 UTC, jaymzh requested changes
You still have lint issues, sorry. If you can fix your trailing white space we'll be happy to merge. Thanks!

2023-08-22 19:40 UTC, jaymzh commented
@dafyddcrosby  is taking this on

2023-08-28 19:50 UTC, dafyddcrosby commented
I've opened #13902 with the cosmetic fix to get this committed

2023-08-29 19:25 UTC, jaymzh commented
Merged in https://github.com/chef/chef/pull/13902

2023-08-29 19:25 UTC, closed without merging