Start documenting chef's dynamic pipeline.
chef/chef pull request #13581
Opened 2023-02-15 16:19 UTC by gcs-devel

## Description

## Related Issue

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2023-02-17 19:09 UTC, tpowell-progress approved these changes

2023-02-17 20:37 UTC, evanahlberg requested changes

2023-02-17 20:37 UTC, evanahlberg commented on docs/dev/ci/README.md
> +2. **Via the Buildkite CLI.** If you have the [Buildkite CLI]({{< ref "/docs/getting-started/integrations.md" >}}) configured, you can trigger a release pipeline manually using the `bk build create`
fix link

2023-02-17 20:37 UTC, evanahlberg commented on docs/dev/ci/README.md
> +3. **Via the Buildkite CLI.** If you have the [Buildkite CLI]() configured, you can trigger a release pipeline manually using the `bk build create` command.
link to cli

2023-02-17 20:37 UTC, evanahlberg commented on docs/dev/ci/README.md
> +3. **Via the Buildkite CLI.** If you have the [Buildkite CLI]() configured, you can trigger a verify pipeline manually using the `bk build create` command.
link to cli

2023-02-21 09:37 UTC, neha-p6 approved these changes

2023-02-21 15:23 UTC, IanMadd approved these changes

2023-02-21 16:21 UTC, merged