Fix json output of cookbook list
chef/chef pull request #13654
Opened 2023-03-29 08:17 UTC by aknarts

## Description
This PR turns the output from the following:
```json
$ knife cookbook list -a -F json
[
  "7-zip                       1.0.2",
  "api_docs                    0.1.0",
  "apt                         1.1.1",
  "ark                         4.0.0  3.1.1  0.9.0  0.3.0",
  "audit-cis                   0.4.0",
  "authenticator               0.1.5  0.1.4",
  "aws-static-ip-ha            0.1.0",
  "aws-tools                   0.0.5"
]
```
to this
```json
$ knife cookbook list -a -F json
{
  "openbsd-sshd": [
    "0.1.0"
  ],
  "couchbase": [
    "0.1.0"
  ],
  "openssh": [
    "0.1.0"
  ],
  "openldap": [
    "1.0.0"
  ],
  "httpd": [
    "0.1.1"
  ],
}
```
The list is different due to ordering and me stripping sensitive information

This has a potential of breaking peoples script if they adjusted to the broken format, that is why this is marked as a breaking change.

## Related Issue
This is a PR for #13653

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2023-04-05 18:34 UTC, williamtheaker commented
I think this closes https://github.com/chef/chef/issues/10404

2023-04-11 19:59 UTC, jaymzh requested changes
For the text version, lets keep the nice justification.

For the JSON, lets pretty-generate it

2023-04-12 09:23 UTC, aknarts commented on knife/lib/chef/knife/core/generic_presenter.rb
> +                versions_by_cookbook
I am sorry but that makes the output way worse...
Your changes produce this:
![Screenshot from 2023-04-12 11-21-23](https://user-images.githubusercontent.com/252905/231414290-d1290494-4468-48a6-9485-47d18a4a47c5.png)
![Screenshot from 2023-04-12 11-21-10](https://user-images.githubusercontent.com/252905/231414296-d75bcb70-d390-44c3-95e8-310c78dcda44.png)

My original changes produce this:
![Screenshot from 2023-04-12 11-22-08](https://user-images.githubusercontent.com/252905/231414378-5161c9cc-ae96-43ac-917e-1613a3b71a90.png)
![Screenshot from 2023-04-12 11-21-48](https://user-images.githubusercontent.com/252905/231414382-0dd5ad6e-05ca-411b-bc2a-2d61ad36050f.png)

It is still formatted properly in the summary section and json is not polluted by things that do not belong to json

2023-05-02 19:45 UTC, jaymzh approved these changes
Ah, because `ui.output` which is where this output goes, does all the formatting for us! I didn't know that (sorry, I'm not as familiar with knife). This looks great.

we SHOULD note that if anyone is parsing the output of `knife cookbook list`, this will bite them, but I think that's OK, that's not an API.

2023-05-02 19:46 UTC, merged