remove eol warning
chef/chef pull request #13742
Opened 2023-05-04 20:43 UTC by Stromweld

## Description
Since EOL is arbitrary based on company releases having a hard coded time doesn't make sense and is causing confusion when triggered and version is still active.

## Related Issue

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2023-05-05 18:29 UTC, tpowell-progress approved these changes

2023-05-09 19:06 UTC, jaymzh commented
Well, we're only in this mess because we moved around 18. But ultimately, it took us a long time to be able to get code out there that will warn people when they're on unsupported versions. If we remove this, and come up with something new it'll be like Chef 24 before it's reliably everywhere, so I'm very very wary of removing this.

Other possibilities:
* Have a special exception for 18
* Have a override file people can touch for a given version

2023-05-09 20:54 UTC, jaymzh commented
OK based on our discussion in the meeting, let's do something like:

1. Update this code to not try to predict the date, but instead just have a date per version, ala

```ruby
deprecation_dates = {
  '17' => ...,
  '18' => ...,
}
```

This can be right in this function, or, alternatively, we could `require_relative` a file that has them which has something like:

```ruby
class Chef
  class Deprecations
    DEPRECATION_DATES = {
      ..
    }
  end
end
```

 The latter has the benefit that they're in easy to find, but the downside that it's pretty trivial for someone to monkeypatch that variable from anywhere in their cookbooks, which normally would be fine, except we want them to use the override mechanism we are going to give them below, so my instinct would be to leave it in the code, but that's up to you.

2. We decided to make the dates the following:
  * Chef 17: 31 Mar 2024 - the same day Ruby 3.0 is deprecated
  * Chef 18: 31 Mar 2025 - one year later, which is the *minimum* deprecation time. We have plenty of time to bump it out, but we don't' want to make the date too far out and imply any guarantee of support yet.

3. Provide an override mechanism for users, and for support. We decided on the following scheme:
* The config file will have a new config `version_deprecation_suppression` (or whatever) which will take a hash. The key is, importantly *the specific minor version for which the warning should be suppressed* (not the major version), and the value is a date up to which we will suppress the warning. Ala:
```ruby
version_deprecation_suppression {
  # we're stuck on 17.0 for a while. But in 17.1 they bumped the deprecation date
  # from 2025 to 2028. We plan to at least move to 17.2 before 2027, so we should
  # ignore the deprecation warning on our current version to then.
  # 
  # However, to work around critical but XYZ, we have to move from 17.0.1 to 17.0.2,
  # which has the same older deprecation date, so ignore it for both.
  '17.0.1' => '2027-05-01',
  '17.0.2' => '2027-05-01',
}
```

Why not just major version? Because then if I upgrade to a significantly newer minor version, I may be masking an updated deprecation date I didn't intend to.

2023-05-16 19:45 UTC, jaymzh requested changes
Just changing status.

2023-05-23 19:17 UTC, closed without merging

2023-05-23 19:17 UTC, tpowell-progress commented
Closing this to start fresh on a new PR mimicking logic for 17