update ::File.exists? to ::File.exist?
chef/chef pull request #13770
Opened 2023-05-30 19:57 UTC by jasonwbarnett

## Description

This removes all uses of deprecated `::File.exists?` so that when Chef adopts Ruby 3.2 there won't be problems. This is also helpful for folks who happen to use Ruby 3.2 when unit testing Chef outside of Chef Workstation.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2023-06-06 19:48 UTC, tpowell-progress commented
@jasonwbarnett looks like some unit specs broke with this change. Any possibility of looking over them to double-check?

2023-06-27 19:48 UTC, jaymzh commented on spec/unit/client_spec.rb
>      expect(File).to receive(:exists?)
this one?

2023-06-27 19:51 UTC, jaymzh requested changes
Looks like there's  still tests that need updating.

2023-07-11 19:41 UTC, jaymzh approved these changes
Nice

2023-07-11 19:47 UTC, jaymzh commented on spec/unit/provider/package/rpm_spec.rb
> +    allow(::File).to receive(:exist?).with("PLEASE STUB File.exist? EXACTLY").and_return(true)
Shouldn't this be `exist?` ?

2023-07-11 19:48 UTC, merged