For building linux-aarch64 support for Effortless pattern
chef/chef pull request #13781
Opened 2023-06-06 05:32 UTC by smandaka

For building linux-aarch64 target for testing effortless pattern for linux-aarch64 target.

## Description
nitially we were getting build error for linux-aarch64 target, after adding "fix_interpreter "${pkg_prefix}/vendor/bin/*" "$_chef_client_ruby" ruby" build was successful. But still getting runtime error while running "chef -version". So then we added line "bundle config --local build.ffi "--with-ldflags=-Wl,-rpath=${LD_RUN_PATH}"

## Related Issue

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2023-06-09 11:48 UTC, smandaka commented
This PR is duplicate of https://github.com/chef/chef/pull/13769

2023-06-27 19:31 UTC, jaymzh requested changes
Dupe of https://github.com/chef/chef/pull/13769

2023-06-28 04:37 UTC, smandaka commented
> Dupe of #13769

Yes. This is duplicate PR. We can close it.

2023-07-06 21:22 UTC, PrajaktaPurohit commented
Closing as a dup of https://github.com/chef/chef/pull/13769

2023-07-06 21:22 UTC, closed without merging