Using an omnibus-software patching mechanism
chef/chef pull request #13787
Opened 2023-06-08 16:20 UTC by vkarve-chef

## Description
In the most recent chef-17 build, there is an issue with incompatible `openssl.so` getting packaged in Windows. This causes runtime failures. This is a workaround to allow for a successful chef-17 release with a patched `openssl.so` on Windows.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2023-06-09 17:04 UTC, johnmccrae commented
I cannot repro the failed choco tests on my local dev node. I am going with this issue being environment specific to those failing nodes. I'll see if I can coax out more details

2023-07-11 19:38 UTC, jaymzh commented
It sounds like this isn't needed per @johnmccrae ...

*IF* we do decide to use this, we should:
1. Link to both the relevant PRs in `omnibus` and `omnibus-software` in the description
2. Explain the ffi/mixlib-shellin changes and how they're related in the description

2023-07-18 19:48 UTC, jaymzh requested changes
Taking this out of the review queue per last week's comment.

2023-09-05 19:43 UTC, closed without merging

2023-09-05 19:43 UTC, tpowell-progress commented
@vkarve-chef closing this out as it seems we've addressed this elsewhere.