Correcting sensitive items being written out
chef/chef pull request #13897
Opened 2023-08-27 23:34 UTC by johnmccrae

## Description
Correcting the issue with Linux users that expose passwords when the attribute 'sensitive' is set to true

## Related Issue

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2023-08-29 19:37 UTC, jaymzh requested changes
Please remove your Gemfile.lock updates.

Code looks good.

2023-09-01 16:20 UTC, tpowell-progress approved these changes

2023-09-05 19:06 UTC, jaymzh approved these changes

2023-09-05 19:31 UTC, jaymzh commented
I think we can close https://github.com/chef/chef/pull/13885 now that this is approved.

2023-09-05 19:33 UTC, tpowell-progress commented
@johnmccrae We're approved aside from the berkshelf failure. Feel free to merge if you're ready to.

2023-09-06 12:40 UTC, merged