Updated the attribute splitting logic to use field_separator
chef/chef pull request #13956
Opened 2023-09-27 12:00 UTC by ashiqueps

## Description

The logic to build the search filter array was hardcoded with splitting the attribute names with a dot only. This was causing issues when there is a dot present in the attribute name, for example a package with version number included. This will not return the correct results. 
```bash
knife search node "packages:libtcl*" -a packages.libtcl8.6.version
```
Eventhough we have an argument `-S(--field-separator SEPARATOR)` to separate the attribute names, because of the hardcoding in the splitting logic, this is also not working. 

I've updated the logic to use the field-separator passed along with the command so that the attributes can be constructed correctly. So, the below command will solve the above issue.

```bash
╰─➤  knife search node "packages:libtcl*" -a packages:libtcl8.6:version -S:
3 items found

node-1:
  packages:libtcl8.6:version: 8.6.12+dfsg-1build1

demo-node:
  packages:libtcl8.6:version: 8.6.12+dfsg-1build1

node-3:
  packages:libtcl8.6:version: 8.6.12+dfsg-1build1
```

## Related Issue

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2023-09-28 12:16 UTC, nikhil2611 approved these changes

2023-10-03 20:01 UTC, tpowell-progress commented
@ashiqueps Can you rebase on current `main` and also add a test for the change to cover the default and field separator specified case?

2023-10-03 20:01 UTC, tpowell-progress requested changes
Please rebase on main and add test for default and alternative separator case.

2023-10-04 08:15 UTC, ashiqueps commented
Hi @tpowell-progress,

I've rebased with main and added specs for the field_separator. Please review.

2023-10-05 19:01 UTC, sanjain-progress approved these changes

2023-10-09 15:17 UTC, tpowell-progress commented on knife/spec/unit/knife/core/ui_spec.rb
> +      it "should return field separator in attribute_field_separator" do
I think I'd rather see that `create_result_filter_from_attributes` responds to a set/unset `attribute_field_separator` vs. testing the set/get of the field separator itself.

2023-10-11 17:03 UTC, tpowell-progress approved these changes

2023-10-12 14:35 UTC, merged