Update platform list with sles-15-X86-64  and support debian arm
chef/chef pull request #14004
Opened 2023-10-10 16:44 UTC by poorndm

## Description

## Related Issue

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] If `Gemfile.lock` has changed, I have used `--conservative` to do it and included the full output in the Description above.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2023-10-10 16:52 UTC, sean-simmons-progress requested changes
https://github.com/chef/chef/blob/99619374d31f2466cad7597dd3abd121f0d93af7/.buildkite/build-test-omnibus.sh#L14

Here you need to add: `debian-10-arm:debian-10-arm`  and `debian-11-arm:debian-10-arm`

2023-10-10 16:53 UTC, sean-simmons-progress commented on .expeditor/release.omnibus.yml
> +  debian-10-arm64:
you can remove these here 30:32

2023-10-10 17:15 UTC, poorndm commented on .expeditor/release.omnibus.yml
> +  debian-10-arm64:
Done

2023-10-17 07:35 UTC, poorndm commented
Ref build log : https://buildkite.com/chef/chef-chef-main-validate-adhoc/builds/755 - Passed

2023-10-18 12:40 UTC, tpowell-progress approved these changes

2023-10-19 14:52 UTC, tpowell-progress commented
> https://github.com/chef/chef/blob/99619374d31f2466cad7597dd3abd121f0d93af7/.buildkite/build-test-omnibus.sh#L14
> 
> Here you need to add: `debian-10-arm:debian-10-arm` and `debian-11-arm:debian-10-arm`

Looks like this still needs to be updated?

2023-10-20 05:47 UTC, poorndm commented
> > https://github.com/chef/chef/blob/99619374d31f2466cad7597dd3abd121f0d93af7/.buildkite/build-test-omnibus.sh#L14
> > Here you need to add: `debian-10-arm:debian-10-arm` and `debian-11-arm:debian-10-arm`
> 
> Looks like this still needs to be updated?

We have  PR :https://github.com/chef/chef/pull/14005  for debian support.

2023-10-20 13:20 UTC, tpowell-progress requested changes
Still looking for changes in regard to @sean-simmons-progress's comment:
> Here you need to add: `debian-10-arm:debian-10-arm` and `debian-11-arm:debian-10-arm`

2023-10-24 20:42 UTC, tpowell-progress approved these changes

2023-10-24 20:43 UTC, tpowell-progress commented
> > > https://github.com/chef/chef/blob/99619374d31f2466cad7597dd3abd121f0d93af7/.buildkite/build-test-omnibus.sh#L14
> > > 
> > > Here you need to add: `debian-10-arm:debian-10-arm` and `debian-11-arm:debian-10-arm`
> > 
> > 
> > Looks like this still needs to be updated?
> 
> We have PR :#14005 for debian support.

But it has a conflict because the change is on the same line, so need a rebase first before we can merge.

2023-10-26 06:23 UTC, poorndm commented
Duplicate of https://github.com/chef/chef/pull/14044

2023-10-26 06:23 UTC, closed without merging