updating the code sign with digicerts HSM, also put some validation i…
chef/chef pull request #14112
Opened 2023-12-02 16:08 UTC by sean-simmons-progress

…n the script

also putting in a temp fix for omnibus tests until we can figure out why Artifactory is not caching this folder correctly

## Description
This solves the issue with windows code singing certs and integrates with digicerts HSM. 

## Related Issue

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] If `Gemfile.lock` has changed, I have used `--conservative` to do it and included the full output in the Description above.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2023-12-02 18:33 UTC, sean-simmons-progress commented
For the internal folks at chef: https://buildkite.com/chef/chef-chef-main-validate-adhoc/builds/897#_

2023-12-04 14:28 UTC, tpowell-progress requested changes

2023-12-04 14:44 UTC, sean-simmons-progress commented on omnibus/omnibus-test.ps1
> +gem install unf_ext -v 0.0.8.2 --source https://rubygems.org/gems/unf_ext
I put that source there as it seems that our instance of artifactory has a problem with how that specific gem is cached, this was a simpler fix vs. upgrading a few versions of artifactory.

If this pr works: https://github.com/chef/chef/pull/14115 we can likely remove lines 119, and 120 on the omnibus-test.ps1

2023-12-04 15:28 UTC, sean-simmons-progress commented on omnibus/omnibus-test.ps1
> +gem install unf_ext -v 0.0.8.2 --source https://rubygems.org/gems/unf_ext
removed that temp fix for now. PR is updated.

2023-12-04 18:39 UTC, tpowell-progress approved these changes

2023-12-04 18:41 UTC, merged