Updating FFI-YAJL
chef/chef pull request #14176
Opened 2024-01-16 15:34 UTC by johnmccrae

## Description
testing version update for ffi-yajl

## Related Issue

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] If `Gemfile.lock` has changed, I have used `--conservative` to do it and included the full output in the Description above.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2024-01-16 19:58 UTC, tpowell-progress commented
@johnmccrae do you have the `bundle update` output?

2024-01-16 19:59 UTC, tpowell-progress requested changes
Clean up and bundle update output

2024-01-16 19:59 UTC, tpowell-progress commented on chef.gemspec
> +  # s.add_dependency "ffi-yajl", "~> 2.2"
Go ahead and delete

2024-01-16 21:35 UTC, johnmccrae commented on chef.gemspec
> +  # s.add_dependency "ffi-yajl", "~> 2.2"
done

2024-01-17 00:43 UTC, tpowell-progress approved these changes

2024-01-17 22:02 UTC, merged