Fixed the issue with log level on the chef config
chef/chef pull request #14294
Opened 2024-03-26 07:54 UTC by ashiqueps

## Description

In the chef config, there are two different options to set the log level. One is the `log_level` and the other is the `verbose`. The verbose has more preference, meaning that if it is set, it will overwrite the log_level based on the verbosity level. 

Currently, If the verbosity is not set, the code will default the log_level to `warn` even if the user specifies a different log_level on the config.rb or the credentials file.

This PR will update that flow so that, if the verbosity is not set, it will use whatever value is already set on the log_level and if that is nil, it will default to `warn`. 

## Related Issue

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] If `Gemfile.lock` has changed, I have used `--conservative` to do it and included the full output in the Description above.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2024-03-26 08:04 UTC, nikhil2611 approved these changes

2024-03-26 19:51 UTC, johnmccrae commented
@nikhil2611 can you take another look at the specs, there are still failures

2024-03-26 20:40 UTC, johnmccrae requested changes
Can you please check the testers again, there are still failures. Cheers

2024-03-27 22:50 UTC, johnmccrae approved these changes

2024-03-27 22:50 UTC, merged