EC and modulo length update for OpenSSL 3 compatibility
chef/chef pull request #14354
Opened 2024-04-23 21:06 UTC by tpowell-progress

## Description

## Related Issue

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] If `Gemfile.lock` has changed, I have used `--conservative` to do it and included the full output in the Description above.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2024-04-24 12:45 UTC, johnmccrae approved these changes

2024-04-24 13:25 UTC, neha-p6 requested changes
Feel we should also run an adhoc build as we are hoping to merge this before our openSSL 3 upgrade is finished, just to sure this doesn't break on openssl 1 on rest of the platforms as well.

2024-04-24 13:55 UTC, tpowell-progress commented
> Feel we should also run an adhoc build as we are hoping to merge this before our openSSL 3 upgrade is finished, just to sure this doesn't break on openssl 1 on rest of the platforms as well.

Running https://buildkite.com/chef/chef-chef-main-validate-adhoc/builds/1430

2024-05-08 04:18 UTC, tpowell-progress commented
@neha-p6 we have a Windows run https://buildkite.com/chef/chef-chef-main-validate-adhoc/builds/1467

2024-05-08 11:38 UTC, neha-p6 commented
> > Feel we should also run an adhoc build as we are hoping to merge this before our openSSL 3 upgrade is finished, just to sure this doesn't break on openssl 1 on rest of the platforms as well.
> 
> Running https://buildkite.com/chef/chef-chef-main-validate-adhoc/builds/1430
@tpowell-progress Looks like we had artifactory failures at some places in the original build but that is blocked testers. Re do a build?

2024-05-08 20:28 UTC, tpowell-progress commented
> > > Feel we should also run an adhoc build as we are hoping to merge this before our openSSL 3 upgrade is finished, just to sure this doesn't break on openssl 1 on rest of the platforms as well.
> > 
> > 
> > Running https://buildkite.com/chef/chef-chef-main-validate-adhoc/builds/1430
> > @tpowell-progress Looks like we had artifactory failures at some places in the original build but that is blocked testers. Re do a build?

Those are the breakages with the current chef-foundation. We can only selectively run adhoc runs.

2024-05-14 20:03 UTC, merged