Fix pagination for supermarket list
chef/chef pull request #14361
Opened 2024-04-29 11:52 UTC by aknarts

## Description
As per the issue, the API limits on the supermarket end have been changed from unlimited to a maximum of 100.

This fix is in accordance with how it is done in `supermarket_show.rb` 

## Related Issue
#14360

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] If `Gemfile.lock` has changed, I have used `--conservative` to do it and included the full output in the Description above.
- [x] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2024-10-08 20:48 UTC, johnmccrae commented
Hi, can you please rebase this and run the unit specs again?

2024-10-29 20:31 UTC, jaymzh requested changes
Can you please rebase? Thanks!

2024-12-10 21:23 UTC, sean-simmons-progress commented
@aknarts 

Can you please rebase?

2025-03-18 20:39 UTC, jaymzh commented
Rebasing via new button.

2026-05-26 20:49 UTC, closed without merging