Updating the client_config_resource
chef/chef pull request #14465
Opened 2024-06-28 21:03 UTC by johnmccrae

## Description
Per this bug: https://chefio.atlassian.net/browse/CHEF-7885, we had previously taken a fix to correct the issue. However, that fix only addressed a problem with the Ohai property and not the policy_persist_run_list property. This fix updates that. 

## Related Issue

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] If `Gemfile.lock` has changed, I have used `--conservative` to do it and included the full output in the Description above.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2024-06-28 21:23 UTC, Stromweld commented
you also need to add to the property `default: false` https://github.com/chef/chef/blob/main/lib/chef/resource/chef_client_config.rb#L196

2024-07-02 15:10 UTC, tpowell-progress commented on lib/chef/resource/support/client.erb
>  <% end -%>
```suggestion
<% end -%>
<%# boolean properties are neither .nil? nor respond to .empty? so they are included below %>
```

2024-07-02 15:11 UTC, tpowell-progress requested changes
Add the comment in case further issues come up or someone decides to refactor.

2024-07-02 16:07 UTC, tpowell-progress approved these changes

2024-07-02 17:21 UTC, johnmccrae commented on lib/chef/resource/support/client.erb
>  <% end -%>
done

2024-07-02 17:22 UTC, merged