Preparing for Chef-18 and Chef-19 release branches
chef/chef pull request #14469
Opened 2024-07-03 15:35 UTC by sean-simmons-progress

This is to create the expeditor agent chef-18, as well as create the new base v19 version.
Also creates the release branch 19 (main), and chef-18. 

## Description

## Related Issue

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] If `Gemfile.lock` has changed, I have used `--conservative` to do it and included the full output in the Description above.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2024-07-03 15:46 UTC, sean-simmons-progress commented
Lets do a screen share / review on this before we merge.

2024-07-03 18:21 UTC, sean-simmons-progress commented
Following https://github.com/chef/chef/blob/main/docs/dev/how_to/bumping_the_major_version.md#create-a-branch-to-fixup-your-new-stable-branch-for-release - will need to complete before merge.

2024-07-09 12:53 UTC, tpowell-progress approved these changes

2024-07-09 14:03 UTC, neha-p6 requested changes
We might first want to merge ohai bump changes https://github.com/chef/ohai/pull/1825/files so that ohai 19 is available on `main` there. 
Then update `VERSION` here to 19.0.0. 
Because here we are missing `Gemfile.lock`, `chef.gemspec`  and `knife.gemspec` which will point to ohai latest (i.e 19) and then run `rake dependencies:update` so that both `Gemfile.lock` and `omnibus/Gemfile.lock` are updated correctly as well.

2024-07-09 20:10 UTC, tpowell-progress requested changes
@sean-simmons-progress I think Neha's mentions of `main` are correct... double-check them at least.

2024-07-11 13:17 UTC, tpowell-progress commented on omnibus/Gemfile.lock
> +    chef (18.4.12)
`bundle update --conservative chef` in `omnibus` directory?

2024-07-11 14:38 UTC, tpowell-progress approved these changes

2024-07-11 16:48 UTC, merged