added nil check for current_record in resource skipped
chef/chef pull request #14582
Opened 2024-08-28 23:13 UTC by jamespdo

after hook resource skipped cause FATAL error when current record is nil and cause entire CDV fail (even tho tests passed successfully). This is ruby fatal error.
## Description

when running CDV for cinc 18.x and 19.x , after hook resource skipped with current record is nil will cause ruby FATAL error because it attempted to set something not exist
## Related Issue

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [X] I have read the **CONTRIBUTING** document.
- [X] I have run the pre-merge tests locally and they pass.
- [X] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [ ] If `Gemfile.lock` has changed, I have used `--conservative` to do it and included the full output in the Description above.
- [X] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2024-09-03 20:31 UTC, tpowell-progress commented
@jamespdo do you have a reproduction test case that you can provide? Trying to understand how to get in this scenario.

2024-09-03 23:13 UTC, jamespdo commented
@tpowell-progress you can step thru the code [here](https://github.com/chef/chef/blob/main/lib/chef/action_collection.rb#L237-L239) and force return nil for `current_record`, then resource skip method get called at the end of :run_completed on chef event handler, it will get evaluated as after hooks, however the nil value will cause the method resource_skipped to err out, hence I added the proposed nil check for current record. I also check for downstream reference and the only thing using current record is printing to std out, which in this case will be empty/nothing as its nil value. but will let after hook finishes successfully, rather than attempt to set .status on nil current record

2024-09-17 20:44 UTC, tpowell-progress commented on lib/chef/action_collection.rb
> +      end
```suggestion
      return if  current_record.nil?
      current_record.status = :skipped
      current_record.conditional = conditional
```

2024-09-17 20:46 UTC, tpowell-progress commented on lib/chef/action_collection.rb
> +      end
Use a guard instead of `unless` block.

2024-09-17 20:47 UTC, tpowell-progress requested changes
Refactoring to make more idiomatic Ruby

2024-09-18 00:46 UTC, jamespdo commented on lib/chef/action_collection.rb
> +      end
updated per request, please rereview

2024-10-01 20:11 UTC, tpowell-progress approved these changes

2024-10-08 20:16 UTC, johnmccrae requested changes
Hi, can you please rebase this and fix the linting issue.

2024-10-29 20:22 UTC, jaymzh approved these changes
Sorry for the delay, this slipped through the cracks. If the tests pass (ignoring the hab test in buildkite, which was known-broken at the time), we'll go ahead and merge. Thanks!

2024-12-03 21:43 UTC, tpowell-progress commented
👋 @jamespdo sorry for the delay, we've gone through and fixed the builds that were holding this up, so if you can rebase so that we can double-check the pipeline, we can get this merged.

2024-12-03 22:32 UTC, jamespdo commented
@tpowell-progress rebased from main

2025-01-14 22:37 UTC, sean-simmons-progress commented
will need to fix this - No product keys are defined for artifactory to promote before we can merge.

2025-01-28 21:39 UTC, johnmccrae approved these changes

2025-02-25 21:44 UTC, jaymzh requested changes
Sorry to request again - but can you rebase one more time?

2025-02-25 22:28 UTC, sean-simmons-progress commented
> Sorry to request again - but can you rebase one more time?
we need to dig into this error, its legit, something cant download from omnitruck / package router:

```
Digest: sha256:c9d207638e8f4c30ca43f29f8d4a9fa7be18af8d37fa96555ee5cbc04464145a
Status: Image is up to date for chefes/omnibus-toolchain-windows-2019:3.0.28
Exception setting "OutputEncoding": "The request is not supported.
"
At line:2 char:1
+ [Console]::OutputEncoding = New-Object -typename System.Text.ASCIIEnc ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationExceptio
   n
    + FullyQualifiedErrorId : ExceptionWhenSetting
 
 
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        Omnitruck                           {Get-ProjectMetada...
There was an error:
	Exception calling "DownloadString" with "1" argument(s): "The remote server returned an error: (404) Not Found."
	The remote server returned an error: (404) Not Found.
Failed to download from https://omnitruck.chef.io/current/chef-foundation/metad
ata?v=3.2.8&p=windows&pv=2019&m=x86_64.
At line:75 char:5
+     throw "Failed to download from $uri."
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to downl...=2019&m=x86
   _64.:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to download from https://omnitruck.chef.i
   o/current/chef-foundation/metadata?v=3.2.8&p=windows&pv=2019&m=x86_64.
```

2025-02-25 22:34 UTC, sean-simmons-progress commented
> > Sorry to request again - but can you rebase one more time?
> > we need to dig into this error, its legit, something cant download `https://omnitruck.chef.io/current/chef-foundation/metad ata?v=3.2.8&p=windows&pv=2019&m=x86_64.` from omnitruck.
> 
> ```
> Digest: sha256:c9d207638e8f4c30ca43f29f8d4a9fa7be18af8d37fa96555ee5cbc04464145a
> Status: Image is up to date for chefes/omnibus-toolchain-windows-2019:3.0.28
> Exception setting "OutputEncoding": "The request is not supported.
> "
> At line:2 char:1
> + [Console]::OutputEncoding = New-Object -typename System.Text.ASCIIEnc ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationExceptio
>    n
>     + FullyQualifiedErrorId : ExceptionWhenSetting
>  
>  
> ModuleType Version    Name                                ExportedCommands
> ---------- -------    ----                                ----------------
> Script     0.0        Omnitruck                           {Get-ProjectMetada...
> There was an error:
> 	Exception calling "DownloadString" with "1" argument(s): "The remote server returned an error: (404) Not Found."
> 	The remote server returned an error: (404) Not Found.
> Failed to download from https://omnitruck.chef.io/current/chef-foundation/metad
> ata?v=3.2.8&p=windows&pv=2019&m=x86_64.
> At line:75 char:5
> +     throw "Failed to download from $uri."
> +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (Failed to downl...=2019&m=x86
>    _64.:String) [], RuntimeException
>     + FullyQualifiedErrorId : Failed to download from https://omnitruck.chef.i
>    o/current/chef-foundation/metadata?v=3.2.8&p=windows&pv=2019&m=x86_64.
> ```



ahh okay this will be fixed when we rebase and re-test. The updated file from main is valid:

https://github.com/chef/chef/blob/main/.buildkite-platform.json

2025-03-18 21:56 UTC, jaymzh commented
Once https://github.com/chef/chef/pull/14913 is finished and merged we'll rebase this (we can do it for you) and it should be good to go.

2025-03-25 23:16 UTC, jaymzh commented
Thanks!

2025-03-25 23:16 UTC, merged