Fix windows plan
chef/chef pull request #14655
Opened 2024-10-14 17:38 UTC by sajjaphani

Fixes the Windows plan that resolves the issue of failing to load the openssl.so file.

## Description

The OpenSSL gem is unable to resolve the OpenSSL libraries installed with core/openssl. This PR installs the OpenSSL gem with flags that point to the core/openssl Habitat package.

## Related Issue

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] If `Gemfile.lock` has changed, I have used `--conservative` to do it and included the full output in the Description above.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2024-10-14 19:35 UTC, johnmccrae requested changes
Phani,

We traced the problem with installing FFI to a busted version of Bundler - v 2.3.36 or later. We have since pinned the version to 2.3.7 until that gets fixed.

Can you back out the changes on lines: 38, 95-99? I just tested your update minus those lines and it works. You'll need to rebase once before you do this. 

Also, this ends up pulling in Openssl 3.3.0.9. We need v 3.0.9. How can we ensure this pulls in the correct version?

2024-10-15 11:06 UTC, sajjaphani commented
> Phani,
> 
> We traced the problem with installing FFI to a busted version of Bundler - v 2.3.36 or later. We have since pinned the version to 2.3.7 until that gets fixed.
> 
> Can you back out the changes on lines: 38, 95-99? I just tested your update minus those lines and it works. You'll need to rebase once before you do this.
This has been addressed. The branch was created from the main branch.
> 
> Also, this ends up pulling in Openssl 3.3.0.9. We need v 3.0.9. How can we ensure this pulls in the correct version?
The core/openssl package is being pulled at version 3.0.9 only. Where do you see version 3.3.0.9?

2024-10-15 12:56 UTC, johnmccrae commented
Hi, I slightly misread the version. I called openssl.exe from pkg_prefix path
[HAB-STUDIO] Habitat:\src> C:\hab\studios\localrepo--chef2\hab\pkgs\chef\ruby31-plus-devkit\3.1.6\20240904124118\msys64\usr\bin\openssl.exe version
OpenSSL 3.3.0 9 Apr 2024 (Library: OpenSSL 3.3.0 9 Apr 2024)

it returned version 3.3.0 - 9 April....

2024-10-15 13:19 UTC, rahulgoel1 commented
@sajjaphani John is mentioning that he is noticing a different version of openssl in the comment above. Pls review that. 
https://github.com/chef/chef/pull/14655#issuecomment-2413842671

2024-10-15 13:28 UTC, neha-p6 commented
> @sajjaphani John is mentioning that he is noticing a different version of openssl in the comment above. Pls review that. [#14655 (comment)](https://github.com/chef/chef/pull/14655#issuecomment-2413842671)

@johnmccrae  The location you are trying to access and the build is accessing seem to be different? https://buildkite.com/chef-oss/chef-chef-main-verify/builds/18221#01929004-5186-47a8-8a1e-ad359484c618/79-130

2024-10-15 14:26 UTC, sajjaphani commented
@johnmccrae @neha-p6 
I am not sure why the OpenSSL from the path (C:\hab\pkgs\chef\ruby31-plus-devkit\3.1.6\20240904124118\msys64\usr\bin\openssl.exe) is reporting version 3.3.0.

I have verified the following:

- hab pkg uninstall chef/ruby31-plus-devkit
- hab pkg install chef/ruby31-plus-devkit -c LTS-2024
- hab pkg exec chef/ruby31-plus-devkit openssl --version
The output shows: `OpenSSL 3.3.0 9 Apr 2024 (Library: OpenSSL 3.3.0 9 Apr 2024)`.

I think this issue may be related to the chef/ruby31-plus-devkit itself. Can you verify this?

2024-10-15 20:25 UTC, tpowell-progress commented
> @johnmccrae @neha-p6 I am not sure why the OpenSSL from the path (C:\hab\pkgs\chef\ruby31-plus-devkit\3.1.6\20240904124118\msys64\usr\bin\openssl.exe) is reporting version 3.3.0.
> 
> I have verified the following:
> 
> * hab pkg uninstall chef/ruby31-plus-devkit
> * hab pkg install chef/ruby31-plus-devkit -c LTS-2024
> * hab pkg exec chef/ruby31-plus-devkit openssl --version
>   The output shows: `OpenSSL 3.3.0 9 Apr 2024 (Library: OpenSSL 3.3.0 9 Apr 2024)`.
> 
> I think this issue may be related to the chef/ruby31-plus-devkit itself. Can you verify this?

@sajjaphani that's just the executable that comes with ruby devkit... check the library version from `irb` itself.

2024-10-15 20:34 UTC, johnmccrae commented
I think the version that is showing up is coming from the Ruby Devkit and not the Openssl version. My local Ruby devkit is showing openssl version == 3.3.2.

I think I see part of the problem, we're using core/openssl which is openssl v 3.3.x. I don't see a version of Openssl 3.0.9 for Windows on bldr - there IS one for Linux though and that is "core/build-tools-openssl". Can that be updated to include a Windows version?

2024-10-16 08:56 UTC, sajjaphani commented
Depending on which `openssl.exe` you invoke, it may report different versions. For example, the version bundled with chef/ruby31-plus-devkit, which includes Ruby from [RubyInstaller 3.1.6-1](https://github.com/oneclick/rubyinstaller2/releases/tag/RubyInstaller-3.1.6-1), has version 1.1.1w (from [RubyInstaller 3.1.5-1](https://github.com/oneclick/rubyinstaller2/releases/tag/RubyInstaller-3.1.5-1), where there is no update to OpenSSL in version 3.1.6).

For Chef Infra, it's important to use OpenSSL version 3.0.9. You can verify this with the following commands
```sh
hab pkg exec ci/chef-infra-client ruby -- --version
ruby 3.1.6p260 (2024-05-29 revision a777087be6) [x64-mingw-ucrt]
hab pkg exec ci/chef-infra-client openssl -- version
OpenSSL 3.0.9 30 May 2023 (Library: OpenSSL 3.0.9 30 May 2023)
hab pkg exec ci/chef-infra-client ruby -e "require 'openssl'; puts OpenSSL::OPENSSL_VERSION"
OpenSSL 3.0.9 30 May 2023
```

In addition, you can also check the build log, which clearly shows the use of core/openssl 3.0.9 and ruby gem 3.2.0:
https://buildkite.com/organizations/chef-oss/pipelines/chef-chef-main-verify/builds/18222/jobs/0192904e-7d1d-469a-8fd4-3b1b38a796cc/log

2024-10-16 13:13 UTC, neha-p6 approved these changes

2024-10-16 13:13 UTC, johnmccrae approved these changes

2024-10-16 13:13 UTC, merged