Prepare hab based chef-infra-client rpm
chef/chef pull request #14772
Opened 2024-12-24 12:26 UTC by sajjaphani

Prepare the Habitat-based Chef Infra Client by leveraging the chef-migrate and Chef Client Habitat tar files.

## Description

This PR includes the script and the spec file necessary to prepare the Habitat-based Chef Infra Client. The script can be executed by running the following command:

```bash
.expeditor/scripts/build-infra-rpm.sh
```

The script requires two tarballs as input:

- Migration Tool Tarball: Contains the migration tools.
- Chef Infra Client Tarball: Exported using the hab pkg export tar command.

The two necessary input files need to be set through environment variables:

```bash
export CHEF_INFRA_MIGRATE_TAR=/path/to/migration-tools_Linux_x86_64.tar.gz
export CHEF_INFRA_HAB_TAR=/path/to/chef-chef-infra-client-19.0.54-20241121145703.tar.gz
```

## Related Issue

https://progresssoftware.atlassian.net/browse/CHEF-18110

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] If `Gemfile.lock` has changed, I have used `--conservative` to do it and included the full output in the Description above.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2025-01-08 14:45 UTC, marcparadise commented on .expeditor/scripts/chef-infra-client.spec
> +/opt/chef/bin
Because /opt/chef/bin is already owned by the chef-infra package, we probably don't want to install anything here. 
Could we instead use a different directory, something like '/opt/chef/migration' or even include it in '/opt/chef/bundle"?

2025-01-08 14:51 UTC, marcparadise requested changes
Overall this looks good, but I had some minor points that I left inline.

2025-01-08 14:51 UTC, marcparadise commented on .expeditor/scripts/chef-infra-client.spec
> +if [ ! -f /opt/chef/bin/chef-client ]; then
/opt/chef/bin/chef-client may not exist, but chef-client could still be installed on the system and available int he path via workstation. In that case, is 'fresh-install' still correct?

2025-01-08 14:51 UTC, marcparadise commented on .expeditor/scripts/chef-infra-client.spec
> +%changelog
Can we exclude this if we're not using it?

2025-01-08 14:51 UTC, marcparadise commented on .expeditor/scripts/chef-infra-client.spec
> +#mkdir -p %{buildroot}/opt/chef
no need to keep commented-out code here

2025-01-08 14:51 UTC, marcparadise commented on .expeditor/scripts/chef-infra-client.spec
> +The full stack of Chef Infra Client
Probably need to check with Product on the wording of the description and summary, I'm not sure that 'full stack of ...' are the right words anymore.

2025-01-08 14:51 UTC, marcparadise commented on .expeditor/scripts/chef-infra-client.spec
> +%define _binary_payload w1.xzdio
We might want to disable compresssion - it will slow down the build without much advantage, because we're primarily shipping two already-compressed tarballs.

2025-01-08 15:29 UTC, sajjaphani commented on .expeditor/scripts/chef-infra-client.spec
> +if [ ! -f /opt/chef/bin/chef-client ]; then
The migration tool has an option to uninstall the Omnibus installation during migration. However, I am not sure whether it accounts for the Workstation. Therefore, I am specifically checking the Omnibus installation here

2025-01-08 15:34 UTC, sajjaphani commented on .expeditor/scripts/chef-infra-client.spec
> +/opt/chef/bin
Would it be a good idea to unpack the migration tool into /opt/chef/migration/bin instead?

2025-01-08 15:42 UTC, Stromweld commented on .expeditor/scripts/chef-infra-client.spec
> +/opt/chef/bin
since new install lives in /hab why aren't we using that directory and in the end there shouldn't be any /opt/chef anything unless using omnibus version. That'll make it easier for customers to understand anything related to hab builds lives in /hab/somewhere and omnibus in /opt/chef instead of 1 tool over here and all others over there. This also then makes Cookbook checks easy to accomodate both by simply checking for the existence of /opt/chef.

2025-01-08 19:43 UTC, jasonheath commented
Adding this to both PRs.  There are many differences in the names of the rpm and deb files. The deb has an extra "chef-" at the beginning of the name that the rpm doesn't.  This is due to the name field used in the rpm specfile and the deb name coming from parsing the tarball name. The deb finds a timestamp the rpm doesn't have.  The rpm has "1.amzn2023.x86_64" that is again driven by the specfile that the deb lacks that.  I don't have a strong opinion on the "naming standard" but I do think the rpm and deb names should be aligned with each other.

```
[ec2-user@jah-mazon | ~/Development]
$ ls chef/*rpm
chef/chef-infra-client-19.0.54-1.amzn2023.x86_64.rpm
```

```
[admin@jah-wah | ~/Development]
$ ls chef/*deb
chef/chef-chef-infra-client-19.0.54-20241121145703.deb
```

2025-01-08 19:58 UTC, jasonheath commented
@sajjaphani, @mwrock: Should there be a check around the presence of the buildkite-agent?  I don't have that installed on my test machine so the script blows up when it gets to that line which makes me feel like it should have such a check.  However, I think its reasonable to argue that this script is in the .expeditor directory structure, so its really kind of expected to be run in a context where buildkite-agent is available, and so such a check isn't something that we need to worry about.  Which way do we break? If in favor of such a check we'd also need to add it to the deb work that @sougata-progress has done.

2025-01-08 21:24 UTC, mwrock commented
yeah instead of `buildkite-agent artifact upload` you can copy the artifact to a local directory and then use the `artifact_paths` in the pipeline's expeditor yaml to point to that path/file. We use that quite a bit in the habitat pipelines.

2025-01-09 05:34 UTC, sajjaphani commented on .expeditor/scripts/chef-infra-client.spec
> +/opt/chef/bin
@marcparadise @Stromweld It appears that using /opt/chef or /hab may have similar drawbacks, as it could interfere with their structures. Could we use a separate directory, /opt/chef-migrate, instead, where bin would hold the binary of the migration tool and bundle would hold the tar file?

2025-01-15 05:28 UTC, sajjaphani commented
> yeah instead of `buildkite-agent artifact upload` you can copy the artifact to a local directory and then use the `artifact_paths` in the pipeline's expeditor yaml to point to that path/file. We use that quite a bit in the habitat pipelines.

Does specifying artifact_paths work for any artifact, even when the final artifacts are not .hart files but .rpm or .deb packages instead?

2025-01-15 05:32 UTC, sajjaphani commented
> Adding this to both PRs. There are many differences in the names of the rpm and deb files. The deb has an extra "chef-" at the beginning of the name that the rpm doesn't. This is due to the name field used in the rpm specfile and the deb name coming from parsing the tarball name. The deb finds a timestamp the rpm doesn't have. The rpm has "1.amzn2023.x86_64" that is again driven by the specfile that the deb lacks that. I don't have a strong opinion on the "naming standard" but I do think the rpm and deb names should be aligned with each other.
> 
> ```
> [ec2-user@jah-mazon | ~/Development]
> $ ls chef/*rpm
> chef/chef-infra-client-19.0.54-1.amzn2023.x86_64.rpm
> ```
> 
> ```
> [admin@jah-wah | ~/Development]
> $ ls chef/*deb
> chef/chef-chef-infra-client-19.0.54-20241121145703.deb
> ```

The prepared RPM aligns with the existing naming structure: https://omnitruck.chef.io/current/chef/packages?v=18
https://packages.chef.io/files/current/chef/18.6.2/amazon/2023/chef-18.6.2-1.amazon2023.x86_64.rpm

2025-01-15 14:21 UTC, mwrock commented
> @mwrock Does specifying artifact_paths work for any artifact, even when the final artifacts are not .hart files but .rpm or .deb packages instead?

Yes. Buildkite has no awareness of hart or deb, etc. It can be any kind of file. If you look at the habitat usage in the pipeline yamls, you will notice we mainly use it for log files.

2025-01-15 17:25 UTC, marcparadise commented on .expeditor/scripts/chef-infra-client.spec
> +if [ ! -f /opt/chef/bin/chef-client ]; then
Let's instead look at declaring a package-level conflict, so that we can't install infra-19 when chef-workstation 'legacy' is installed.  
That will let us avoid the entire class of problems that arise trying to manually manage conflicting files across packages. 

This can be better supported once workstation itself is released with habitat.

2025-01-16 05:44 UTC, sajjaphani commented
@rahulgoel1 
Removed the upload functionality from the script, as it will be handled by the export task. The export task can look for a corresponding .deb or .rpm file in the current directory, typically the root of Chef, and then upload the artifact.

2025-01-16 05:52 UTC, sajjaphani commented on .expeditor/scripts/chef-infra-client.spec
> +if [ ! -f /opt/chef/bin/chef-client ]; then
Prevents to proceed if chef-workstation is installed: https://github.com/chef/chef/pull/14772/commits/10c403f58b4e4d08c26484cb5b461cae0b7e2983

2025-01-16 06:39 UTC, sajjaphani commented on .expeditor/scripts/chef-infra-client.spec
> +The full stack of Chef Infra Client
I've updated the summary and description to:
"Chef Infra Client is an agent that runs locally on each node managed by the Chef Infra Server."

I will make further updates based on product input later.

2025-01-16 06:41 UTC, sajjaphani commented on .expeditor/scripts/chef-infra-client.spec
> +/opt/chef/bin
Changed the directory to place the migration binary and bundle into `/hab/migration`. The binary is now located in `/hab/migration/bin`, and the infra tarball is stored in `/hab/migration/bundle`.

2025-01-16 07:09 UTC, sajjaphani commented
@marcparadise @rahulgoel1 
As discussed, I've changed the location of the migration tools to /hab/migration. After this change, the chef-client installation through migration will exit without installing and display the following message:

```
Detected existing hab-based Chef-Client installation.
No migration required. Exiting.
```

The issue arises because the chef-migrate tool checks if `/hab` exists. If it does, the tool will not continue. Currently, we cannot use the `/hab` directory with the migration tool. We either need to modify the `chef-migrate` tool or choose a different directory.

2025-01-16 08:08 UTC, sajjaphani commented
> @marcparadise @rahulgoel1 As discussed, I've changed the location of the migration tools to /hab/migration. After this change, the chef-client installation through migration will exit without installing and display the following message:
> 
> ```
> Detected existing hab-based Chef-Client installation.
> No migration required. Exiting.
> ```
> 
> The issue arises because the chef-migrate tool checks if `/hab` exists. If it does, the tool will not continue. Currently, we cannot use the `/hab` directory with the migration tool. We either need to modify the `chef-migrate` tool or choose a different directory.

Ignore this; it is happening because the uninstall process is not handled by chef-migrate, leaving some links behind after the RPM is uninstalled.

2025-01-16 14:05 UTC, rahulgoel1 commented on .expeditor/scripts/chef-infra-client.spec
> +Summary:        Chef Infra Client is an agent that runs locally on each node managed by the Chef Infra Server.
"Chef infra client is an agent for configuration management"

2025-01-21 14:20 UTC, marcparadise approved these changes

2025-01-22 14:19 UTC, merged