Release file handles after extraction
chef/chef pull request #14770
Opened 2024-12-20 12:23 UTC by nielsbuus

## Description

There is a bug in the current implementation of archive_file which causes it to lock the compressed file for remainder of the chef-client run. This prevents you from deleting a compressed file after extracting it within the same execution.

The bug stems from incorrect usage of the Archive::Reader API. When opening a file using open_filename, you need to explicitly close it again afterwards to release the lock that your Ruby process holds on the compressed file.

## Types of changes

- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] If `Gemfile.lock` has changed, I have used `--conservative` to do it and included the full output in the Description above.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2025-01-07 19:56 UTC, tpowell-progress commented
👋 @nielsbuus Thanks for your contribution... Can you `-s` your commit to ✔️ the DCO and  rebase on `main` to clean up the build status.

2025-01-07 21:41 UTC, tpowell-progress requested changes
Good catch... proposing that we convert to block format in comments.

2025-01-07 21:41 UTC, tpowell-progress commented on lib/chef/resource/archive_file.rb
> +            archive.close
Looks like [`open_filename`](https://github.com/chef/ffi-libarchive/blob/545d3948e7a78835da48737c1490516905fad2e6/lib/ffi-libarchive/writer.rb#L5) takes a block, and so this would be cleaner and automatically `ensure` closure if these calls were converted to that pattern.

2025-01-14 21:40 UTC, tpowell-progress approved these changes

2025-01-14 21:40 UTC, jaymzh approved these changes
Thanks! This looks great.

2025-01-14 22:27 UTC, nielsbuus commented
Thanks guys. I notice that a few of the jobs are failing, but the errors do not look directly related to this change. Not sure if there is more that can I do?

2025-01-16 15:48 UTC, tpowell-progress commented
@nielsbuus do you have the opportunity to rebase against `main`? The build fixes should be in place to validate that there aren't other issues.

2025-01-17 11:47 UTC, nielsbuus commented
> @nielsbuus do you have the opportunity to rebase against `main`? The build fixes should be in place to validate that there aren't other issues.

Looks like the pipeline is green now. Notice that I haven't tested the code changes myself by building and running the chef-client as I am not familiar with that process. If you have any concerns about the coverage of the automated pipeline testing, perhaps you want to do some additional testing before releasing a new version of the chef-client.

2025-01-28 21:37 UTC, merged